### ISSUE TITLE
Cant use your pkg with tsconfig module targetd to ES6

### ISSUE THREAD

**Issue by pramod16686** [nitinet/es-cache#2]
Hi Nitin,

Nice package for caching functionality. I request to implement one feedback.
My Typescript project has requirement to use module: ES6 in tsconfig file. 
Your library is using dynamic module export which is not supported in ES6. Can you please modify that so I can use it in my project?

switch (options.storeType) {
			case types.StoreType[types.StoreType.local]:
				module = await import('./store/Local.js');
				break;

			case types.StoreType[types.StoreType.redis]:
				module = await import('./store/Redis.js');
				break;

			case types.StoreType[types.StoreType.memcache]:
				module = await import('./store/Memcache.js');
				break;
			default:
				module = await import('./store/Local.js');
		}

**Comment by nitinbansal1989** [comment]
Hello @pramod16686 

Thanks for the feedback but currently the package has optional dependencies of multiple packages like redis, memcache, class-transfromer, etc. These are loaded dynamically based on the use case.
If we remove dynamic import then it will become mandatory to add these packages as dependencies. This is just to keep this module as light weight as possible.
Please let me know if you come across any way to remove the dynamic import while keping these dependencies as optional.
Thanks.
